extends:
  - eslint:recommended
  - plugin:node/recommended

plugins:
  - node
  - promise

env:
  mocha: true
  node: true

rules:
  indent: [2, "tab"]
  no-console: 0
  semi: 2
  strict: 0
  node/no-unsupported-features: [ 2, { "version": 4 }]
