language: node_js
node_js:
  - '6.10'
  - '8.10'
  - '10'
install:
  - yarn install
script:
  - yarn run lint
  - yarn run test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage
deploy:
  provider: npm
  email: accounts@acloud.guru
  api_key:
    secure: nMZVsye4+DHAPIcIHy2DxycA+55c6hxW+tTubIZZSR3W0Z5IfIDE1CUPixzlEG4mScvmFGUUHvKL52rfBMAA6XB/TLCH+05B9D1xxk+pJog/af+ueG5QKW3v5GVbSuyTxpoec5/YUiz5gYLnysdRejrWgLhMOGGzlWHUuLaQIheFy0c+UkLA0c9E4NnBHo3kmNzHmF41f/FqXfDPJqaJYRnpyTG3sZCAQQ4rhjdMsLfPn1728fRN328uGs6iAZK1G7G2WlGyWZ6UG5bF9DClyXvgwhAIaZl+hbRm7GArfVxOlg1Jh/ioRgXhTTyzJGYJLlCb1t/qVcSFDSQn14OIaQ6nxpbiH8wYUxSHuGGyY5ZMjAt7D7kfJ7SrTUn65dUZhwrj/N0Hb8yynDDphnBwoRekmEROiCQ2SRprMiY4fjusx4gbLCM9uP99UyjC6bKkT1OUjxeX2MdgZ5F2xC89p+7bMNuI0Bhjsg2rDGdAjQf9YMxvMherRJeL8lTnkKkhn4gK1iwaxC5YkBeigaaqLhhzV4l95vWKy47r6IT4zwA0oxgOuLCzq5co2camdvkCu01osWceon/ORJH7vic2pkbYd7IWF9PVjo4z+BJDXPDqpu9jI392knoJiSRSCaBLBJSN02cYJIZjbUONEe2XU73W19/ZreChQpSOFdz8Lcs=
  on:
    tags: true
    repo: ACloudGuru/serverless-plugin-aws-alerts
    branch: master
    node: '10'
notifications:
  slack:
    secure: KOs6IURWgOVOiB6haTYcaQVVueM2/0mLiQbZEV++DsrNIZkd/ArqU+ufr18jCb7z4mWJ+TNTj4QSiwFFjaB2o2ZF+0/2hzGzj/y41E/Qir9MswdgpdZSpPcPBDYB8IK1o+1FlX81o1jOibeQyUv+CMOej8aXk/kYlEvtxqec9NqRdPQHM56V7AizrjYOZGH7MVcxOYmvvmcWWAEfzg5SxzgJvVNbXZvqkMut9kcpD6rOMUYtXbIQ22Xy3lfJ5MHCckQMFKYUwZSjwmhWOayrevNfXPdiAPCuxVXm0Hgzyzm8vNSntmet+j9mdqS5dYRiteoAXN+Th0fgf9l/nhkPpoNW7VIJMUmjMaxbxb/McU2+1h/ZGF+OG10kTZzX+5Bw7nKrtUUAs0bKQ8hfEWh7YTgTKPfLOd5ieR+9LGUy/bqfTfvoBdP8bi//wY72VyrfYmDCUmWfE9X0u8VaMR/cOhKT6WAueoseOXebpvKo1wcxHI2GH0SHDRWnIWQrSQuE/3sdan8ek3ZCiQBv74n4cCcTN0hV3KFk2EG9ENMtL1+3FZ924vqW1yV1LzME8CrzVxwJ08cauzfAPTABa2m/iXWyGgr0O5BALjrAHqIuTWCCjwKZhfLrZnSrfzOPBggkzPqqlpMHBAqo7+1sOSYZMSglLZaLpm9055/wn2OBfYg=
