language: node_js
node_js:
  - '4.4'
  - '6.10'
  - '8'

install:
  - yarn install

script:
  - yarn run lint
  - yarn run test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage

deploy:
  provider: npm
  email: accounts@acloud.guru
  api_key:
    secure: JqcYlIg0jeevnDw8RmstnCjss/f9Vz+7yCU4WpVPmU8SARRYz+mKBou4mBJb+zj/63JownMMSrNg/FR8rNrdJnPkACM3O+OaAdxKKfpYAprsSffq8fbYzsRX6zehCos4rzBH0P23TxuCFKD81ZzYUy+ZlR4ISVWrPjzznBlfmGbgamhxgIx5Wv5QJQte2TqGwQq4qQ4R1m2tamKOV6vQqnbJTD1GyqIO8nbWtKro2ft3qdmejgah3+34KKD7U7bFn6UVT/2W7jlWihePjHkYhyLzezjuDn/sIhXqO6mfcMUYUVVGYQ+9YrSfvl1bPL3/0ZpKG5169qyK8VfDLdb1q8+sWAGb0PwQd2sTnQ2cLbMZ3aeQxLwARl4+/dSF3ImZTT2OBTMnM5CeUmgr86pm/Aqif0SJ2bNLSwSth8QX8MDs8YZX0EFSuxXUsVZ3SHaB1bbtwkTeaO4hlwKvSJ5+35aNNdztH9uvq1iFFL8clL5ZDuJvcZ40nWNIMWbnH8RI1cAxrHfjVd3OSs+49ZrJTmtZLYXz4sXOPa5gMQMkKdTId7IkPckmjKutSB6yxXw/j0CqBzoxeVmX36e/UWS9Q5uP3a8Wm9vIfPc2mGsgVibmaQLGYJv7YUKZAHhzT6eybDHqT0AiRgS9RLpCrn+0xwIfRW+YGL00YE7eFR7rzk0=
  on:
    tags: true
    repo: ACloudGuru/serverless-plugin-aws-alerts
    branch: master
    node: '4.4'

notifications:
  slack:
    secure: KOs6IURWgOVOiB6haTYcaQVVueM2/0mLiQbZEV++DsrNIZkd/ArqU+ufr18jCb7z4mWJ+TNTj4QSiwFFjaB2o2ZF+0/2hzGzj/y41E/Qir9MswdgpdZSpPcPBDYB8IK1o+1FlX81o1jOibeQyUv+CMOej8aXk/kYlEvtxqec9NqRdPQHM56V7AizrjYOZGH7MVcxOYmvvmcWWAEfzg5SxzgJvVNbXZvqkMut9kcpD6rOMUYtXbIQ22Xy3lfJ5MHCckQMFKYUwZSjwmhWOayrevNfXPdiAPCuxVXm0Hgzyzm8vNSntmet+j9mdqS5dYRiteoAXN+Th0fgf9l/nhkPpoNW7VIJMUmjMaxbxb/McU2+1h/ZGF+OG10kTZzX+5Bw7nKrtUUAs0bKQ8hfEWh7YTgTKPfLOd5ieR+9LGUy/bqfTfvoBdP8bi//wY72VyrfYmDCUmWfE9X0u8VaMR/cOhKT6WAueoseOXebpvKo1wcxHI2GH0SHDRWnIWQrSQuE/3sdan8ek3ZCiQBv74n4cCcTN0hV3KFk2EG9ENMtL1+3FZ924vqW1yV1LzME8CrzVxwJ08cauzfAPTABa2m/iXWyGgr0O5BALjrAHqIuTWCCjwKZhfLrZnSrfzOPBggkzPqqlpMHBAqo7+1sOSYZMSglLZaLpm9055/wn2OBfYg=
