coverage:
  status:
    project:
      default:
        target: auto
        threshold: null

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - master
