coverage:
  status:
    project:
      default:
        target: auto
        threshold: 90%
        base: auto
        flags:
          - unit
        paths:
          - "src"
        branches:
          - master
        if_ci_failed: error
        informational: false
        only_pulls: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - master
